/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testpmi;

import dBConn.Conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.RMIConnector;

/**
 *
 * @author shay
 */
public class getPmiController {

    public Connection conn;
    //public dbconn dbConn;

    public getPmiController() throws Exception {

        // Creating DBConnection object
        //dbConn = new dbconn();
    }

    public int getNewPmi() throws Exception {
        //conn = dbConn.getConnection();
        int nilai = 1;
//        try {
//            String sql = "SELECT pmi_i "
//                    + "FROM autogenerated_pmi";
//            PreparedStatement ps = conn.prepareStatement(sql);
//            ResultSet rs = ps.executeQuery();
//            if (rs.next()) {
//                nilai = rs.getInt("pmi_i");
//                sql = "INSERT INTO autogenerated_pmi(pmi_i) "
//                        + "VALUES(?)";
//                PreparedStatement ps2 = conn.prepareStatement(sql);
//                ps2.setInt(1, nilai + 1);
//                ps2.execute();
//            }
//            System.out.print("nilai lah "+nilai);
//
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
        RMIConnector rmic = new RMIConnector();
        String sql = "SELECT pmi_i "
                + "FROM autogenerated_pmi ORDER BY pmi_i desc";
        ArrayList<ArrayList<String>> seq = Conn.getData(sql);
        ArrayList<String> seqNo = seq.get(0);
        for (int w = 0; w < seqNo.size(); w++) {
            nilai = Integer.parseInt(seq.get(w).get(0));
            int newNilai = nilai + 1;
            String sql2 = "INSERT INTO autogenerated_pmi(pmi_i)VALUES(" + newNilai + ")";
            rmic.setQuerySQL(Conn.HOST, Conn.PORT, sql2);

        }
        return nilai;
    }
}
